version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ecommerce-order-db
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_USER=adzi
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ecommerce_app
    ports:
      - "5432:5432"
    volumes:
      - db_order_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      # test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce-order-service
    networks:
      - ecommerce-network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
  

networks:
  ecommerce-network:
    external: true

volumes:
  db_order_data:
